export default [
  [`Amqui`, `Radio autre que FM, pronom relatif`],
  [`Argenteuil`, `Dollar, Yeux`],
  [`Arvida`, `Elle enleva le contenu une deuxième fois`],
  [`Beaupré`, `Joli champs`],
  [`Beaconsfield`, `Champs anglophone de jambon`],
  [`Bécancour`, `Bouche d'oiseau, douze mois, marche vite`],
  [`Bellechasse`, `Jolie poursuite`],
  [`Belleterre`, `Jolie planète`],
  [`Beloeil`, `Joli globe oculaire`],
  [`Boisbriand`, `Forêt lumineuse`],
  [`Bonaventure`, `Agréable péripétie`],
  [`Boucherville`, `Agglomération des débiteurs de viande`],
  [`Bromont`, `Dude, Colline`],
  [`Cap-Chat`, `Péninsule qui n'est pas un chien`],
  [`Cap-Santé`, `Péninsule qui n'est pas malade`],
  [`Charlemagne`, `Roi des francs`],
  [`Châteauguay`, `Palais heureux`],
  [`Chicoutimi`, `Défèque, frappe, petit en language familier, note musicale`],
  [`Coaticook`, `Raton d'amérique centrale qui cuisine en anglais`],
  [`Contrecoeur`, `À l'envers d'un organe`],
  [`Contrecoeur`, `Malgré soi`],
  [`Deux-Montagnes`, `Moins que trois grosses collines`],
  [`Dorval`, `Fait dodo, vallée`],
  [`Drummondville`, `Instrument de percussion sur la cité`],
  [`Escoumins`, `Pluriel, tient la tête, au bout des bras`],
  [`Etchemins`, `(Les) Liaison, sentiers`],
  [`Fermont`, `Montagne de métaux magnétique`],
  [`Forestville`, `Agglomération dans le bois anglophone`],
  [`Grosse-Île`, `Corpulent atoll`],
  [`Havre-Saint-Pierre`, `Port de l'apôtre`],
  [`Issoudun`, `Il lie métaliquement un [...]`],
  [`Joliette`, `Petite beauté`],
  [`Jonquière`, `Anneau, pronom relatif, avant aujourd'hui`],
  [`Kamouraska`, `Qu'un sentiment à danse jamaïcaine`],
  [`L'Ancienne-Lorette`, `Très vieille lorette`],
  [`Lac-Sergent`, `Étendue d'eau militaire`],
  [`Lachine`, `L'Empire du Milieu`],
  [`Lachute`, `La débâcle`],
  [`La Tuque`, `Le chapeau qui tient au chaud`],
  [`Longueuil`, `Globe oculaire étiré`],
  [`Malartic`, `Douloureux pôle`],
  [`(La) Malbaie`, `Douleur, petit fruit`],
  [`Matapédia`, `À moi, à toi, à la fin de wiki`],
  [`Matane`, `À moi, à toi, négation`],
  [`Métis-sur-Mer`, `Autochtone à l'océan`],
  [`Mingan`, `Une partie du corps et son vêtement`],
  [`Mirabel`, `Au centre du pain, plus gros qu'une souris, joli`],
  [`Montmagny`, `Colline, à moi, Gross National Income`],
  [`Mont-Royal`, `Colline de sa majesté`],
  [`Mont-Tremblant`, `Colline qui frissonne`],
  [`Murdochville`, `Parois, Docteur, Municipalité`],
  [`Neuville`, `Municipalité récente`],
  [`Notre-Dame-des-Prairies`, `Vierge des champs`],
  [`Notre-Dame-du-Portage`, `Vierge du transport`],
  [`Percé`, `Troué`],
  [`Pincourt`, `Conifère pas très grand`],
  [`Pont-Rouge`, `Gros viaduc couleur sang`],
  [`Portneuf`, `Cochon récent`],
  [`Prévost`, `Champs, jeune vache`],
  [`Québec`, `Plate-forme marine, bisou`],
  [`Richelieu`, `Emplacement pas pauvre du tout`],
  [`Rimouski`, `S'esclaffe, pas dur, sport de neige`],
  [`Rivière-du-Loup`, `Cours d'eau appartenant au canin`],
  [`Rouyn`, `Pneu, quoi!?`],
  [`Saint-Hilarion`, `Rieur béni chargé positivement ou négativement`],
  [`Saint-Paul-de-l'Île-aux-Noix`, `Apôtre de l'atoll aux arachides`],
  [`Sept-Île`, `Est-ce qu'il connaît?`],
  [`Shawinigan`, `Félin, positif, négation, tient la main au chaud`],
  [`Sherbrooke`, `Dispendieux, ruisseau anglophone`],
  [`Tadoussac`, `Pile soyeuse emballée`],
  [`Trois-Rivière`, `Moins de quatre cours d'eau`],
  [`Verchères`, `Gobelet dispendieux`],
  [`Yamachiche`, `Il détient une chiche qui m'appartient`],
  [`Yamaska`, `Il détient mon style musical d'origine Jamaïquaine`],
];
